2014-11-23 11:57:58
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/threads.py", line 113, in handler
  File "./sftp/commands.py", line 332, in run
  File "./sftp/commands.py", line 480, in do_operation
  File "./sftp/file_transfer.py", line 34, in handler
  File "./sftp/ftp_transport.py", line 839, in put
  File "./sftp/ftp_transport.py", line 330, in handle_ftp_error
ConnectionError: Active mode error, please set ftp_passive_mode to true in sftp-config.json
2014-11-29 23:12:22
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/threads.py", line 113, in handler
  File "./sftp/commands.py", line 332, in run
  File "./sftp/commands.py", line 480, in do_operation
  File "./sftp/file_transfer.py", line 34, in handler
  File "./sftp/ftp_transport.py", line 518, in get
  File "./sftp/file_transfer.py", line 333, in handle_get_dirs
  File "./sftp/ftp_transport.py", line 484, in cd
  File "./sftp/ftp_transport.py", line 189, in handle_ftp_error
  File "./sftp/ftp_transport.py", line 483, in do_cd
  File "./sftp/file_transfer.py", line 246, in encode
  File ".\encodings\cp1252.py", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 10-11: character maps to <undefined>
2014-12-17 02:53:21
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/threads.py", line 113, in handler
  File "./sftp/commands.py", line 332, in run
  File "./sftp/commands.py", line 480, in do_operation
  File "./sftp/file_transfer.py", line 34, in handler
  File "./sftp/file_transfer.py", line 432, in list
  File "./sftp/ftp_transport.py", line 635, in ls
ConnectionError: Active mode error, please set ftp_passive_mode to true in sftp-config.json
2014-12-17 02:53:25
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/threads.py", line 113, in handler
  File "./sftp/commands.py", line 332, in run
  File "./sftp/commands.py", line 480, in do_operation
  File "./sftp/file_transfer.py", line 34, in handler
  File "./sftp/file_transfer.py", line 432, in list
  File "./sftp/ftp_transport.py", line 635, in ls
ConnectionError: Active mode error, please set ftp_passive_mode to true in sftp-config.json
2014-12-17 02:53:32
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/threads.py", line 113, in handler
  File "./sftp/commands.py", line 332, in run
  File "./sftp/commands.py", line 480, in do_operation
  File "./sftp/file_transfer.py", line 34, in handler
  File "./sftp/file_transfer.py", line 432, in list
  File "./sftp/ftp_transport.py", line 635, in ls
ConnectionError: Active mode error, please set ftp_passive_mode to true in sftp-config.json
2014-12-17 02:53:38
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/threads.py", line 113, in handler
  File "./sftp/commands.py", line 332, in run
  File "./sftp/commands.py", line 480, in do_operation
  File "./sftp/file_transfer.py", line 34, in handler
  File "./sftp/ftp_transport.py", line 839, in put
  File "./sftp/ftp_transport.py", line 330, in handle_ftp_error
ConnectionError: Active mode error, please set ftp_passive_mode to true in sftp-config.json
2014-12-17 02:53:51
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/threads.py", line 113, in handler
  File "./sftp/commands.py", line 332, in run
  File "./sftp/commands.py", line 480, in do_operation
  File "./sftp/file_transfer.py", line 34, in handler
  File "./sftp/ftp_transport.py", line 839, in put
  File "./sftp/ftp_transport.py", line 330, in handle_ftp_error
ConnectionError: Active mode error, please set ftp_passive_mode to true in sftp-config.json
2014-12-17 23:25:47
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/threads.py", line 113, in handler
  File "./sftp/commands.py", line 332, in run
  File "./sftp/commands.py", line 480, in do_operation
  File "./sftp/file_transfer.py", line 34, in handler
  File "./sftp/ftp_transport.py", line 839, in put
  File "./sftp/ftp_transport.py", line 330, in handle_ftp_error
ConnectionError: Active mode error, please set ftp_passive_mode to true in sftp-config.json
2014-12-17 23:25:58
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/threads.py", line 113, in handler
  File "./sftp/commands.py", line 332, in run
  File "./sftp/commands.py", line 480, in do_operation
  File "./sftp/file_transfer.py", line 34, in handler
  File "./sftp/ftp_transport.py", line 839, in put
  File "./sftp/ftp_transport.py", line 330, in handle_ftp_error
ConnectionError: Active mode error, please set ftp_passive_mode to true in sftp-config.json
2015-01-15 23:15:50
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/commands.py", line 1174, in run
  File ".\os.py", line 157, in makedirs
WindowsError: [Error 183] : u'E:\\baidu\\ftp\\0577dc.com\\template\\red\\pcache'
2015-07-06 01:14:55
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/threads.py", line 113, in handler
  File "./sftp/commands.py", line 332, in run
  File "./sftp/commands.py", line 480, in do_operation
  File "./sftp/file_transfer.py", line 34, in handler
  File "./sftp/ftp_transport.py", line 839, in put
  File "./sftp/ftp_transport.py", line 330, in handle_ftp_error
ConnectionError: Active mode error, please set ftp_passive_mode to true in sftp-config.json
2015-07-18 16:54:23
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/threads.py", line 113, in handler
  File "./sftp/commands.py", line 332, in run
  File "./sftp/commands.py", line 480, in do_operation
  File "./sftp/file_transfer.py", line 34, in handler
  File "./sftp/ftp_transport.py", line 839, in put
  File "./sftp/ftp_transport.py", line 330, in handle_ftp_error
ConnectionError: Active mode error, please set ftp_passive_mode to true in sftp-config.json
2015-07-30 20:29:14
Traceback (most recent call last):
  File "./sftp/threads.py", line 15, in run_with_except_hook
  File "./sftp/threads.py", line 113, in handler
  File "./sftp/commands.py", line 332, in run
  File "./sftp/commands.py", line 480, in do_operation
  File "./sftp/file_transfer.py", line 34, in handler
  File "./sftp/ftp_transport.py", line 839, in put
  File "./sftp/ftp_transport.py", line 330, in handle_ftp_error
ConnectionError: Active mode error, please set ftp_passive_mode to true in sftp-config.json
